export const ComputeIntegrations = [
    {
        name: 'Airflow',
        image: '/integrations/airflow.png',
        description:
            "Use Aqueduct's API to deploy workflows onto your Apache Airflow cluster but with deeper visibility.",
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Conda',
        image: '/integrations/conda.png',
        description: 'Conda gives you strong Python environment isolation, so you can use your favorite libraries.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Databricks',
        image: '/integrations/databricks.png',
        description: "Launch Aqueduct workflows on top of the Databricks' Jobs API for on-demand Spark clusters.",
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Kubernetes',
        image: '/integrations/kubernetes.png',
        description: 'Launch Aqueduct operators as Kubernetes pods with full control over what resources you use.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'AWS Lambda',
        image: '/integrations/lambda.png',
        description: "Use Lambda's serverless functions to run your Aqueduct workflows with no configuration.",
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Apache Spark',
        image: '/integrations/spark.png',
        description: 'Run Aqueduct workflows on your existing Spark clusters to scale your machine learning.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Ray',
        image: '/integrations/ray.png',
        description: 'Use Ray to distribute your Python execution from your Aqueduct workflows.',
        comingSoon: true,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Google Cloud Functions',
        image: '/integrations/gcf.png',
        description: "Google Cloud's serverless functions allow you to run code with no configuration.",
        comingSoon: true,
        invertLogo: false,
        brightenLogo: false,
    },
];

export const DataIntegrations = [
    {
        name: 'AWS Athena',
        image: '/integrations/athena.png',
        description: 'AWS Athena allows you to run scalable SQL queries over data stored in your S3 buckets.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'BigQuery',
        image: '/integrations/bigquery.svg',
        description: "BigQuery is Google Cloud's scalable cloud data warehouse.",
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Google Cloud Storage',
        image: '/integrations/gcs.png',
        description: 'Use Google Cloud Storage for object storage within the GCP ecosystem.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'MariaDB',
        image: '/integrations/mariadb.png',
        description: 'MariaDB is an open-source fork of MySQL with a fully-compatible MySQL API.',
        comingSoon: false,
        invertLogo: true,
        brightenLogo: false,
    },
    {
        name: 'MongoDB',
        image: '/integrations/mongodb.png',
        description: 'MongoDB gives you scalable, flexible document storage in the cloud.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'MySQL',
        image: '/integrations/mysql.png',
        description: "MySQL is one of the world's most popular relational databases.",
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Postgres',
        image: '/integrations/postgres.png',
        description: "Postgres is the world's most popular open-source RDBMS.",
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Redshift',
        image: '/integrations/redshift.png',
        description: 'AWS Redshift is a highly-scalable data warehouse.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'AWS S3',
        image: '/integrations/s3.png',
        description: 'AWS S3 is a highly-scalable, extremely flexible object storage system.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Snowflake',
        image: '/integrations/snowflake.png',
        description: 'Snowflake is a highly-scalable cloud data warehouse that runs across clouds.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'SQLite',
        image: '/integrations/sqlite.png',
        description: 'SQLite is a powerful, in-process relational database.',
        comingSoon: false,
        invertLogo: false,
        brightenLogo: true,
    },
    {
        name: 'DynamoDB',
        image: '/integrations/dynamodb.png',
        description: 'AWS DynamoDB is a low-latency key-value and document database.',
        comingSoon: true,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Redis',
        image: '/integrations/redis.png',
        description: 'Redis is an open-source in-memory database and caching layer.',
        comingSoon: true,
        invertLogo: false,
        brightenLogo: false,
    },
    {
        name: 'Delta Lake',
        image: '/integrations/deltalake.png',
        description: 'The first storage framework that enables you to architect a Lakehouse.',
        comingSoon: true,
        invertLogo: false,
        brightenLogo: false,
    },
];

export const AllIntegrations = [...ComputeIntegrations, ...DataIntegrations];
